// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMvtKx-I-4VFbU1tXZKX_AZ58f54fcEk',
    appId: '1:1055541672882:web:17755562e14eb9941542ab',
    messagingSenderId: '1055541672882',
    projectId: 'jboxserver',
    authDomain: 'jboxserver.firebaseapp.com',
    storageBucket: 'jboxserver.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNqBMaj7LB8IpLyYayjLfPAC3B0OcmBjk',
    appId: '1:1055541672882:android:0ca0de059e75af1a1542ab',
    messagingSenderId: '1055541672882',
    projectId: 'jboxserver',
    storageBucket: 'jboxserver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6zgNp9dheYB_35sJYX4NYbPZWrHeoziY',
    appId: '1:1055541672882:ios:2faf90427bb7f45f1542ab',
    messagingSenderId: '1055541672882',
    projectId: 'jboxserver',
    storageBucket: 'jboxserver.appspot.com',
    iosBundleId: 'gr.techzombie.jbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6zgNp9dheYB_35sJYX4NYbPZWrHeoziY',
    appId: '1:1055541672882:ios:2faf90427bb7f45f1542ab',
    messagingSenderId: '1055541672882',
    projectId: 'jboxserver',
    storageBucket: 'jboxserver.appspot.com',
    iosBundleId: 'gr.techzombie.jbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJMvtKx-I-4VFbU1tXZKX_AZ58f54fcEk',
    appId: '1:1055541672882:web:080bfca1285174651542ab',
    messagingSenderId: '1055541672882',
    projectId: 'jboxserver',
    authDomain: 'jboxserver.firebaseapp.com',
    storageBucket: 'jboxserver.appspot.com',
  );
}
